server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrx-order80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

ribbon:
  ReadTimeout: 8000

feign:
  hystrix:
    enabled: true
